version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE: mongodb+srv://shehab:igOMm7E70gOylex4@cluster0.6d17ddw.mongodb.net/restaurant?retryWrites=true&w=majority
      JWT_SECRET: My-100321-SuperDuperr-Sealed-Key
      JWT_EXPIRY: 30d
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
